config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :uploads
  resources :users
  resources :sessions, only: %i[new create destroy]
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upload.rb
class Upload < ApplicationRecord
  has_many_attached :files
  belongs_to :user

  before_destroy :detach_files
  validates :name, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false }
  before_validation :sanitize_list

  def created?
    with_lock do
      save
    end
  end

  def updated?(params)
    with_lock do
      update(params)
    end
  end

  private

  def sanitize_list
    return if files.size < 2

    file_set = {}

    files.each do |file|
      check = file.blob.checksum

      file.purge if file_set[check].present?

      file_set[check] = file.blob
    end
  end

  def detach_files
    files.purge
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :uploads

  validates_presence_of :name, :password_digest
  validates :email, presence: true, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :reroute_valid_session

  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :reroute_valid_session, only: :new

  def new; end

  def create
    user = User.find_by_email(params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{user.name}"
      redirect_to uploads_url
    else
      flash[:warning] = "Email or password is incorrect"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
    flash[:success] = "You have logged out. Please come back soon!"
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :reroute_invalid_session
  before_action :set_upload, only: %i[show edit update destroy]
  before_action :confirm_files_attached, only: %i[create]

  def index
    @uploads = current_user.uploads
  end

  def show; end

  def new
    @upload = current_user.uploads.new
  end

  def edit; end

  def create
    @upload = current_user.uploads.new(upload_params)

    if @upload.created?
      if @upload.files.attached?
        flash[:success] = "Upload successful."
        redirect_to @upload
      end
    else
      render :new
      flash[:error] = @upload.errors.full_messages.to_sentence
    end
  end

  def update
    if @upload.updated?(upload_params)
      redirect_to @upload
      flash[:success] = "Upload was successfully updated."
    else
      redirect_to edit_uploads_path(@upload)
      flash[:warning] = @upload.errors.full_messages.to_sentence
    end
  end

  def destroy
    @upload.destroy
    redirect_to uploads_url
    flash[:success] = "Upload was successfully destroyed."
  end

  private

  def set_upload
    @upload = current_user.uploads.find(params[:id])
  end

  def upload_params
    params.require(:upload).permit(:name, :about, files: [])
  end

  def confirm_files_attached
    unless upload_params[:files].present?
      redirect_to new_upload_path
      flash[:warning] = "No files attached for upload!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :reroute_valid_session, only: %i[new]
  before_action :set_user, only: %i[show edit update destroy]

  def index
    redirect_to signup_path
  end

  def show
    redirect_to uploads_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to uploads_path
      flash[:success] = "Account creation successful"
    else
      redirect_to signup_path
      flash[:error] = @user.errors.full_messages.to_sentence
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User account was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def reroute_invalid_session
    unless current_user
      redirect_to root_path
      flash[:notice] = "Please login to continue"
    end
  end

  def reroute_valid_session
    redirect_to uploads_path if current_user.present?
  end

  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when "success" then "alert-success"
    when "warning" then "alert-warning"
    when "error" then "alert-danger"
    when "alert" then "alert-warning"
    when "notice" then "alert-info"
    else flash_type.to_s
    end
  end
end

app/helpers/upload_helper.rb
module UploadHelper
  def discard_file(file)
    file.purge
  end

  def icon_path(file)
    case file.content_type
    when "image/jpeg" then file
    when "image/png" then file
    when "application/pdf" then "pdf-icon.png"
    when "application/doc" then "doc-icon.png"
    when "video/mp4" then "mp4-icon.png"
    else "file-icon.png"
    end
  end
end

app/views/home/index.html.erb
<div class="landing-main">
  <div class="welcome-text">
    <h1>Welcome to File Easy</h1>
    <p>Backing up and sharing files have never been this easy</p>
  </div>

  <div class="landing-image">
    <img class="landing-image image-fluid" src="https://i1.wp.com/blog.gonitro.com/wp-content/uploads/2015/09/College-Document-Sharing.gif"/>
  </div>

  <div class="join-options">
    <p>
      <%= link_to "Sign Up", signup_path %> or 
      <%= link_to "Log In", login_path %> to continue
    </p>
  <div>
</div>

app/views/layouts/_flash.html.erb
<div class="container alert-container">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show float-center">
      <%= msg %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  <% end %> 
</div>

app/views/layouts/_footer.html.erb
<div class="footer-main fixed-bottom">
  <p class="copyright-text">
    ©<%= Time.now.year %> File Easy. All Rights Reserved
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/">File Easy</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user.present? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= user.email.upcase %>
          </a>
          <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
            <a class="nav-link" href=<%= uploads_path %> >My Uploads</a>
            <div class="dropdown-divider"></div>
            <a class="nav-link" href=<%= logout_path %> >Logout</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href=<%= signup_path %> >Sign up</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href= "<%= login_path %>" >Login</a>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileEasy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
  </head>

  <body>
    <div className="main-wrapper">
      <%= render 'layouts/navbar', user: current_user %>

      <div class="main">
        <%= yield %>
      </div>

      <%= render 'layouts/flash', flash: flash %>

    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/uploads/_card.html.erb
<div class="card" style="width: 15rem;">
  <%= image_tag icon_path(upload.files.first),
  class: "card-img-top img-thumbnail img-fluid", alt: "Card image cap" %>

  <div class="card-body">
    <p class="card-title">
      <small class="text-muted">Collection name: </small> <%= upload.name %>
    </p>
    <p class="card-text">
    <small class="text-muted">Description: </small> 
    <% if upload.about.present? %>
      <%= upload.about %>
    <% else %>
      <small class="text-muted">This upload has no description.</small> 
    <% end %>
    </p>

    <hr/>

    <div class="card-actions d-flex flex-wrap justify-content-around">
      <span data-toggle="tooltip" 
      data-placement="bottom" title="View uploaded files in this collection">
        <%= link_to "#{upload.files&.size} files", upload, class: "btn btn-primary" %>
      </span>
      
      <span data-toggle="tooltip" 
      data-placement="bottom" title="Delete this collection">
        <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, upload, method: :delete, data: { confirm: 'Are you sure? This cannot be undone' }, class: "btn btn-small btn-danger float-right" %>
      </span>
    </div>
  </div>
</div>

app/views/uploads/_file_image.html.erb
<% unless file.previewable? %>
  <%= link_to image_tag(icon_path(file), size: 80, class: "mr-3", alt: "File"), rails_blob_path(file, disposition: 'preview')%>
<% else %>
  <%= image_tag icon_path(file), size: 80, class: "mr-3", alt: "file" %>
<% end %>

app/views/uploads/_form.html.erb
<div class="upload-form form">
  <%= form_with(model: upload, local: true) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :about %>
    </div>

    <%= form.file_field :files, multiple:true, direct_upload: true %>

    <div class="actions">
      <%= submit_tag "Upload files" %>
    </div>
  <% end %>
</div>

app/views/uploads/_pagination.html.erb
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <% total_pages.times do |page| %>
      <% if page == current_page - 1 %>
        <li class="page-item active"><a class="page-link" href="#"><%= page + 1 %></a></li>
      <% else %>
        <li class="page-item"><a class="page-link" href="#"><%= page + 1 %></a></li>
      <% end %>
    <% end %>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>

app/views/uploads/edit.html.erb
<div class="edit-upload-page page-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "My Uploads", uploads_path%></li>
    <li class="breadcrumb-item"><%= link_to @upload.name, @upload %></li>
    <li class="breadcrumb-item active"> Edit Collection </li>
  </ol>

  <h2>Edit Collection</h2>
  <div class="edit-upload-page-content d-flex  justify-content-around">
    <div class="edit-upload-form">
      <%= render 'form', upload: @upload %>
    </div>

    <div class="existing-files-container container">
      <p>Existing files for this collection</p>

      <div class="existing-files d-flex flex-wrap">
        <% @upload.files.each do |file| %>
          <span style="width: 85px; height: 85px"; data-toggle="tooltip"
          data-placement="bottom" title=<%= file.blob.filename.instance_variable_get(:@filename).split(" ").join("_") %> >
            <%= render 'file_image', file: file %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/uploads/index.html.erb
<div class="all-uploads-page page-container">
  <h1>My Uploads <span class="float-right" data-toggle="tooltip"
  data-placement="bottom" title="Upload new files"><%= link_to '<i class="fas fa-folder-plus"></i>'.html_safe, new_upload_path %></span></h1>
  <hr/>
  
  <% if @uploads.present? %>
    <div class="uploads-container d-flex flex-wrap p-2 justify-content-center">
      <% @uploads.each do |upload| %>
        <%if upload.files.present?%>
          <%= render 'card', upload: upload %>
        <% end %>
      <% end %>
    </div>

    <% if @uploads.size > 10 %>
      <%= render 'pagination', current_page: 1, total_pages: 2 %>
    <% end %>
  <% else %>
    <h5>You do not have any uploaded files. You can start by uploading your favourite photo</h5>
  <% end %>
</div>

app/views/uploads/new.html.erb
<div class="new-upload-page page-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "My Uploads", uploads_path%></li>
    <li class="breadcrumb-item active"> New Upload </li>
  </ol>

  <h1>New Upload</h1>

  <div class="new-upload-form">
    <%= render 'form', upload: @upload %>
  </div>
</div>

app/views/uploads/show.html.erb
<div class="upload-details-page page-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "My Uploads", uploads_path%></li>
    <li class="breadcrumb-item active"><%= @upload.name %></li>
  </ol>

  <div class="uploads-page-content">
    <div class="uploads-info-bar">
      <h2><%= @upload.name %>
        <span class="float-right" data-toggle="tooltip"
        data-placement="bottom" title="Upload new files"><%= link_to '<i class="fas fa-folder-plus"></i>'.html_safe, edit_upload_path(@upload) %></span>
      </h2>
      <p>Description: <%= @upload.about %></p>
      <p>
        <small class="text-muted"> Created at </small>
        <%= @upload.created_at.utc.getlocal.strftime("%-I:%M %P (%B %m, %Y)") %> <small class="text-muted"> and last updated at </small><%= @upload.updated_at.utc.getlocal.strftime("%-I:%M %P (%B %m, %Y)") %>
      </p>
    </div>

    <div class="uploaded-files-list d-flex flex-wrap p-2">
      <% @upload.files.each do |file| %>
        <div class="media upload-list-file-container">
          <%= render 'file_image', file: file %>

          <div class="media-body align-self-center">
            <p class="mt-0 mb-1"><%= file.blob.filename.instance_variable_get(:@filename) %></p>
            
            <%= link_to "download", file, download: file%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
</div>

app/views/users/_signup_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%= form_tag users_path, { autocomplete: "off" } do |form| %>
    <div class="field">
      <%= label_tag :name %>
      <%= text_field_tag :name %>
    </div>
    <div autocomplete="off" class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>
    <div autocomplete="off" class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Sign up" %>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="page-container">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Home", root_url%></li>
    <li class="breadcrumb-item active">Signup</li>
  </ol>

  <div class="signup-page page-content">
    <h1>Sign up</h1>

    <div class="form auth-form signup-form">
      <%= render 'signup_form', user: @user %>
    <div>

    <p>Already have an account? <%= link_to 'Login', login_path %> </p>
  </div>

  <div class="landing-background"></div>
</div>